# -------------------------------------------------------------------
# 1. TID2013: 传统图像质量评价数据集 (IQA)
# -------------------------------------------------------------------

# spearman.exe 计算 Spearman 等级相关系数 (SROCC)
# kendall.exe 计算 Kendall 等级相关系数 (KROCC)
TID2013:
  name: "TID2013"
  task_type: "iqa"
  data_type: "image"
  mos_min: 0.242
  mos_max: 7.214

  paths:
    root: "datasets/TID2013"   # 数据集根目录路径
    data: "distorted_images"
    metadata: "."

  metadata:
    mos_file: "mos_with_names.txt"



# -------------------------------------------------------------------
# 2. KoNViD-1k: 真实场景视频质量评价数据集 (VQA)
# -------------------------------------------------------------------
KoNViD-1k:
  name: "KoNViD-1k"
  task_type: "vqa"
  data_type: "video"
  mos_min: 1.220
  mos_max: 4.640

  paths:
    root: "datasets/KoNViD-1k"
    data: "KoNViD-1k_videos"
    metadata: "KoNViD-1k_metadata"

  metadata:
    mos_file: "KoNViD_1k_mos.csv"



# -------------------------------------------------------------------
# 3. T2VQA-DB: 文本到视频/含文本视频质量评价数据集 (VQA)
# -------------------------------------------------------------------
T2VQA-DB:
  name: "T2VQA-DB"
  task_type: "vqa"
  data_type: "video"
  mos_min: 0.0
  mos_max: 5.0

  paths:
    root: "datasets/T2VQA-DB"
    data: "T2VQA-DB"
    metadata: "."

  metadata:
    mos_file: "info.txt"
